<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo $service?> <?php echo ' | '.$product_name;?></title>
    <link rel="stylesheet" href="semantic.min.css">
</head>
<body>
<div class="ui large top fixed menu transition visible" style="display: flex !important;">
    <div class="ui container">
        <div class="header item">API_DOC<code>(1.0)</code></div>
        <a class="item" href="list">文件列表</a>
        <a class="item" href="api?f=<?php echo $_GET['f'];?>">接口列表</a>
        <a class="active item">文档详情</a>
        <a class="item" href="index">使用说明</a>
    </div>
</div>

<div class="ui text container" style="max-width: none !important; margin-top: 50px;">
    <div class="ui floating message">
        <h2 class='ui header'>接口：
            <?php echo ($service ? '<a href="list?m='.$service.'&f='.$_GET['f'].'&reload=1">'.$service.'</a>' : '--'); ?>
        </h2>
        <h3>作者：<?php echo $author; ?></h3>
        <br/>
        <span class='ui teal tag label'>
            <?php echo ($description ? $description : '//请检测函数标题描述');?>
        </span>

        <div class="ui raised segment">
            <span class="ui red ribbon label">接口说明</span>
            <div class="ui message">
                <p> <?php echo ($descComment ? $descComment : '//请使用@desc 注释');?></p>
            </div>
        </div>

        <h3>接口参数</h3>
        <table class="ui red celled striped table" >
            <thead>
            <tr>
                <th>参数名字</th>
                <th>类型</th>
                <th>是否必须</th>
                <th>默认值</th>
                <th>其他</th>
            </tr>
            </thead>
            <tbody>
            <?php
                foreach ($params as $key => $val){
                    echo '<tr>';
                    echo '<td>'.$val['1'].'</td>';
                    echo '<td>'.$val['0'].'</td>';
                    echo '<td>'.$val['2'].'</td>';
                    echo '<td>'.$val['3'].'</td>';
                    echo '<td>'.$val['4'].'</td>';
                    echo '</tr>';
                }
            ?>
            </tbody>
        </table>

        <h3>返回结果</h3>
        <table class="ui green celled striped table" >
            <thead>
            <tr>
                <th>返回值</th>
                <th>类型</th>
                <th>说明</th>
            </tr>
            </thead>
            <tbody>
            <?php
            if (!empty($returns)) {
                foreach ($returns as $item) {
                    $name = $item[1];
                    $type = isset($typeMaps[$item[0]]) ? $typeMaps[$item[0]] : $item[0];
                    $detail = $item[2];
                    echo '<tr>';
                    echo '<td>'.$name.'</td>';
                    echo '<td>'.$type.'</td>';
                    echo '<td>'.$detail.'</td>';
                    echo '</tr>';
                }
            }
            ?>
            </tbody>
        </table>

<!--        <div class="ui blue message">-->
<!--            <strong>温馨提示：</strong> 此接口参数列表根据后台代码自动生成。-->
<!--        </div>-->
    </div>
</div>
</body>
</html>