#!/bin/bash
# change the PATH
cur_dir=$(pwd)
Stack=$1

# make sure current user is root
if [ $(id -u) != "0" ];then
    echo "+--------------------------------------+"
    echo "| WARNNING: You should run it as root  |"
    echo "+--------------------------------------+"
    exit 1
fi

start()
{
    echo "+--------------------------------------+"
    echo "| NOTICE: fphp server is starting...   |"
    echo "+--------------------------------------+"
    cd ${cur_dir}
    php7 index.php 2>&1
    if [ $? -eq 0 ];then
        echo "+--------------------------------------+"
    	echo "| NOTICE: fphp server start done!      |"
        echo "+--------------------------------------+"
    else
        echo "+------------------------------------------------------------------------------------+"
        echo "| fphp server is not normally start, You should manual check it or try it later...   |"
        echo "+------------------------------------------------------------------------------------+"
    fi
}

stop()
{
    echo "+--------------------------------------+"
    echo "| NOTICE: fphp server is stopping...   |"
    echo "+--------------------------------------+"
    `cat ./Master.pid|xargs kill -15` 2>&1
    if [ $? -eq 0 ];then
        echo "+--------------------------------------+"
        echo "| NOTICE: fphp server is stopped       |"
        echo "+--------------------------------------+"
    else
        echo "+------------------------------------------------------------------------------------+"
        echo "| fphp server is not normally stopped,You should manual check it or try it later...  |"
        echo "+------------------------------------------------------------------------------------+"
    fi
}

restart()
{
    stop
    if [ $? -eq 0 ];then
        sleep 1;
        start;
    fi
}

if [ $# -eq 1 ];then
    case "${Stack}" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
        exit 1
        ;;
    esac
else
    echo "usage: $0 {start|stop|restart}"
fi
