
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>在线接口列表<?php echo ' | '.$product_name;?></title>
    <link rel="stylesheet" href="assets/semantic.min.css">
</head>
<body>
<div class="ui large top fixed menu transition visible" style="display: flex !important;">
    <div class="ui container">
        <div class="header item">API_DOC<code>(1.0)</code></div>
        <a class="item" href="list">文件列表</a>
        <a class="active item">接口列表</a>
        <a class="item">文档详情</a>
        <a class="item" href="index">使用说明</a>
    </div>
</div>
<div class="ui text container" style="max-width: none !important; margin-top: 50px;">
    <div class="ui floating message">
        <h1 class="ui header">接口列表</h1>
        <table class="ui black celled striped table">
            <thead>
            <tr>
                <th>#</th>
                <th>接口服务</th>
                <th>接口名称</th>
                <th>更多说明</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $num = 1;
            if (!empty($methods)) {
                foreach ($methods as $key => $item) {
                    $NO = $num++;
                    echo '<tr>';
                    echo '<td>'.$NO.'</td>';
                    echo '<td><a href="doc?f='.$file.'&m='.$item['name'].'">'.$item['service'].'</a></td>';
                    echo '<td>'.$item['title'].'</td>';
                    echo '<td>'.$item['desc'].'</td>';
                    echo "</tr>";
                }
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
</body>
</html>
