<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>WIKI<?php echo ' | '.$product_name;?></title>
<link rel="stylesheet" href="http://ols7jf5ge.bkt.clouddn.com/semantic.min.css">
<link type="text/css" rel="stylesheet" href="http://ols7jf5ge.bkt.clouddn.com/chnobean.jsonviewer.css" />
<script type="text/javascript" src="http://ols7jf5ge.bkt.clouddn.com/chnobean.jsonviewer.js"></script>
</head>

<body>
<div class="ui large top fixed menu transition visible" style="display: flex !important;">
  <div class="ui container">
    <div class="header item">API_DOC<code>(1.0)</code></div>
    <a class="item" href="list">文件列表</a>
<!--    <a class="item">接口列表</a>-->
<!--    <a class="item">文档详情</a>-->
    <a class="active item" href="debug">调试工具</a>
    <a class="item" href="index">使用说明</a>
  </div>
</div>

<div class="ui text container" style="max-width: none !important; margin-top: 50px;">
  <div class="ui floating message">
    <span class='ui teal tag label'>接口配置</span>
      <div class="ui message">
          <form class="ui form">
              <div class="field">
                  <label>接口名称：如ucenter/member/list</label>
                  <input type="text" name="name" placeholder="接口名称" value="<?php echo $name;?>">
              </div>
              <div class="field">
                  <label>接口参数：如 string | array | int </label>
                  <input type="text" name="params" placeholder="接口参数" value="<?php echo $params;?>">
              </div>
              <button class="ui button" type="submit">提交测试</button>
          </form>
      </div>
    <span class='ui teal tag label'>返回值</span>
    <div class="ui message">
        <div id="return_container"></div>
    </div>
  </div>
</div>
</body>

<script>
    var return_values =JSON.parse('<?php echo json_encode($return);?>');
    var jsonViewerData = chnobean.jsonviewer.domify(return_values);
    document.getElementById('return_container').appendChild(jsonViewerData.rootElement);
</script>
</html>
