<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>WIKI<?php echo ' | '.$product_name;?></title>
<link rel="stylesheet" href="http://ols7jf5ge.bkt.clouddn.com/semantic.min.css">
<link type="text/css" rel="stylesheet" href="http://ols7jf5ge.bkt.clouddn.com/chnobean.jsonviewer.css" />
<link href="http://ols7jf5ge.bkt.clouddn.com/dist/jsoneditor.css" rel="stylesheet" type="text/css">

    <style>
        #jsoneditor{
            height: 400px;
        }
    </style>
<script src="http://ols7jf5ge.bkt.clouddn.com/js/jquery-3.1.1.min.js"></script>


<script type="text/javascript" src="http://ols7jf5ge.bkt.clouddn.com/chnobean.jsonviewer.js"></script>

<script src="http://ols7jf5ge.bkt.clouddn.com/ace.js"></script>

<script src="http://ols7jf5ge.bkt.clouddn.com/dist/jsoneditor-minimalist.js"></script>

<style>

</style>
</head>

<body>
<div class="ui large top fixed menu transition visible" style="display: flex !important;">
  <div class="ui container">
    <div class="header item">API_DOC<code>(1.0)</code></div>
    <a class="item" href="list">文件列表</a>
<!--    <a class="item">接口列表</a>-->
<!--    <a class="item">文档详情</a>-->
    <a class="active item" href="debug">调试工具</a>
    <a class="item" href="index">使用说明</a>
  </div>
</div>

<div class="ui text container" style="max-width: none !important; margin-top: 50px;">
  <div class="ui floating message">
    <span class='ui teal tag label'>接口配置</span>
      <div class="ui message">
        <div class="ui form">
          <div class="field">
              <label>接口名称：如member/list</label>
              <input type="text" id="service_name" placeholder="接口名称" value="<?php echo $name;?>">
          </div>
        </div>
      </div>
      <div class="ui message">

          <div class="field">
              <label>接口参数：满足http协议get方法的参数形势，如：id=1&name=xiaoxijin</label>
              <div id="jsoneditor"></div>
          </div>
          <button id="submit" class="ui button">提交测试</button>

      </div>
    <span class='ui teal tag label'>返回值</span>
    <div class="ui message">
        <div id="return_container"></div>
    </div>
  </div>
</div>
</body>

<script>
    // create the editor
    var container = document.getElementById('jsoneditor');
    var options = {
        modes: ['code'],
        mode: 'code',
        ace: ace
    };
    var json = JSON.parse('<?php echo json_encode($params);?>');
    var editor = new JSONEditor(container, options, json);


    $('#submit').click(function(){

        $.post('/debug',{
            "name":$("#service_name").val(),
            "params":JSON.parse(editor.getText())
        },function (data) {
            $parseData = JSON.parse(data);
            $('#service_name').val($parseData.name);
            editor.setText(JSON.stringify($parseData.params));
            var jsonViewerData = chnobean.jsonviewer.domify($parseData.return);
           $("#return_container").html(jsonViewerData.rootElement);
        });
        return false;
    });

    var return_values =JSON.parse('<?php echo json_encode($return);?>');
    var jsonViewerData = chnobean.jsonviewer.domify(return_values);
    $("#return_container").html(jsonViewerData.rootElement);
</script>
</html>
