<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>WIKI<?php echo ' | '.$product_name;?></title>
  <link rel="stylesheet" href="http://ols7jf5ge.bkt.clouddn.com/semantic.min.css">
</head>
<body>
<div class="ui large top fixed menu transition visible" style="display: flex !important;">
  <div class="ui container">
    <div class="header item">API_DOC<code>(1.0)</code></div>
    <a class="item" href="list">文件列表</a>
<!--    <a class="item">接口列表</a>-->
<!--    <a class="item">文档详情</a>-->
    <a class="item" href="debug">调试工具</a>
    <a class="active item">使用说明</a>
  </div>
</div>

<div class="ui text container" style="max-width: none !important; margin-top: 50px;">
  <div class="ui floating message">
    <span class='ui teal tag label'>说明</span>
      <div class="ui message">
        Api文档是自动根据api 代码注释生成。为了强制按规范来注释api services.
          接口的访问域必须是public。
      </div>

      <div class="ui raised segment">
          <span class="ui red ribbon label">端口说明：</span>
          <div class="ui message">
              <p>正式 api 服务http协议端口号为：<?php echo $http_port;?></p>
              <p>正式 api 服务tcp协议端口号为：<?php echo $tcp_port;?></p>
              <p>正式 open api 开放服务http协议端口号为：<?php echo $open_http_port;?></p>
          </div>
      </div>
    <span class='ui teal tag label'>Api接口注释实例：</span>
    <div class="ui message">

      <pre>
/**
 * 通用数据接口批量获取一组列表数组 （接口的标题，没有（@）符号，以‘*’号开始）
 * @author xijin.xiao&lt;xiaoxijin@jcy.cc&gt; （实现接口的作者）
 * @desc 通用数据接口批量获取一组列表数组，筛选条件为：$params （更多的描述）
 * @param array $params mixed   无   数据类型服务的通用方法
          （接口参数描述，按空格区分，
          第1列为参数类型，如：array,int,string等
          第2列为参数实际名称 如：$params
          第3列为是否必填 ，必填用：mixed,选填用：optional
          第4列为参数的实际默认值，可为：null '' string，没有就不填
          第5列为参数的详细
          @param 行的整体描述第1，2，3列为必填，4，5列为选填，不可超过5列
          如有多个参数，可另起一行描述
          ）
 * @return array  $data  返回列表数组
         （接口返回值描述，按空格区分，每个接口都必须要有返回值
          第1列为返回值类型，如：array,int,string，bool等
          第2列为匹配第一列类型的实际值 如：$data
          注意：$data，只有当不知道数据类型返回值的元素具体是哪些时候，才能用，为数组类型返回值的全局通用描述，
          第3列为是否必填 ，必填用：mixed,选填用：optional
          第4列为参数的实际默认值，可为：null '' string，没有就不填
          第5列为参数的详细
          @param 行的整体描述第1，2，3列为必填，4，5列为选填，不可超过5列
          如有多个参数，可另起一行描述
          ）
 * @return bool   false  sql参数错误,查不到数据
          （一般情况下，每个接口，都需要有个false的返回值类型，用来通知调用者，这个接口是否按预定逻辑完成功能）
 * @return int list[].id   用户ID
 * @return int list[].name 用户名称
          （如果能够确定接口的返回值具体信息，也可按以上方式描述）
 */
public function list($params){
{
    return [];
}
      </pre>

    </div>
  </div>
</div>
</body>
</html>
